---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

platforms:
#  - name: ubuntu-18.04
  - name: centos-7

suites:
  - name: default
    provisioner:
      policyfile: policyfiles/base.rb
    verifier:
      inspec_tests:
        - test/integration/default
    #    - name: dev-sec/linux-baseline      
    #  controls:
    #    - package-08
    attributes:
